### ISSUE TITLE
Add dashboards for logs in Grafana

### ISSUE THREAD

**Issue by nvucinic** [nvucinic/obstack#1]
- add dashboards for logs in grafana

**Comment by lrenjic** [comment]
Added in 'template' folder.
It is not possible to directly load files from values.yaml when using remote charts, so we need to use ConfigMaps to inject dashboards. Extra manifests are in 'template' folder, Helm uses that folder by default.
CM data is loaded from json files. There needs to be a CM per dashboard because of K8s CM size limit.
